version: '3.7'

services: 
    web_app:
        build: ./web_app
        command: python app.py
        restart: unless-stopped
        volumes: 
            - ./web_app:/usr/src/app
        ports:
            - 5000:5001
        env_file: 
            - ./.env.dev
        environment: 
            - VIRTUAL_HOST: "questions-answers.arrosid.com"
        depends_on: 
            - db
    db:
        image: postgres:12-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
            - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
        environment: 
            - POSTGRES_USER=q_user
            - POSTGRES_PASSWORD=q_password
            - POSTGRES_DB=q_db

volumes: 
    postgres_data:

networks:
  default:
    external:
      name: nginx-proxy