version: '3.7'

services: 
    web_app:
        build: ./web_app
        command: python app.py
        restart: unless-stopped
        volumes: 
            - ./web_app:/usr/src/app
        ports:
            - 5000:5001
        env_file: 
            - ./.env.dev
        depends_on: 
            - db
    db:
        image: postgres:12-alpine
        volumes: 
            - postgres_data:/var/lib/postgresql/data/
        environment: 
            - POSTGRES_USER=question_user
            - POSTGRES_PASSWORD=question_password
            - POSTGRES_DB=question_db

volumes: 
    postgres_data:
